### ISSUE TITLE
Can't transfer a file larger than approx 500KB in size. Socket closed by remote peer!

### ISSUE THREAD

**Issue by yasiriqbal** [nplexity/xmpp-file-transfer-demo#31]
Incoming File Transfer:
Error Domain=XMPPIncomingFileTransferErrorDomain Code=-1 "Socket disconnected before transfer complete." UserInfo={NSLocalizedDescription=Socket disconnected before transfer complete.}

Outgoing File Transfer:
Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}

It transfers well with file size smaller than approximately 500KB.
I have reached here solving a lot of bugs and problems! please help me!
Server = Openfire!

**Comment by yasiriqbal** [comment]
This is the log on server

2016.03.16 09:55:18 org.jivesoftware.openfire.filetransfer.proxy.ProxyConnectionManager - Error during file transfer 
java.net.SocketException: Software caused connection abort: socket write error 
at java.net.SocketOutputStream.socketWrite0(Native Method) 
at java.net.SocketOutputStream.socketWrite(Unknown Source) 
at java.net.SocketOutputStream.write(Unknown Source) 
at java.io.DataOutputStream.write(Unknown Source) 
at org.jivesoftware.openfire.filetransfer.proxy.ProxyOutputStream.write(ProxyOutputStream.java:39) 
at org.jivesoftware.openfire.filetransfer.proxy.DefaultProxyTransfer.doTransfer(DefaultProxyTransfer.java:141) 
at org.jivesoftware.openfire.filetransfer.proxy.ProxyConnectionManager$2.run(ProxyConnectionManager.java:313) 
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
at java.util.concurrent.FutureTask.run(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source)
